#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Two-Interval 2AFC with 1-up/2-down adaptive staircase
-----------------------------------------------------
- Purpose: Estimate detection threshold using 2AFC and 1-up/2-down rule (~70.7% correct).
- Intervals: Two per trial; one contains signal at current level; the other is reference (silence or noise).
- Rule: 2 consecutive correct -> level DOWN one step; 1 incorrect -> level UP one step.
- Stop: after a set number of reversals or max trials.
- Output: CSV log + printed threshold estimate (mean of last N reversals).

Dependencies (recommended for real audio):
    pip install numpy sounddevice

If audio libraries are unavailable, the script switches to a SIMULATED OBSERVER
mode to demonstrate the staircase logic without sound playback.

Author: (Generated by ChatGPT)
License: MIT
"""
from __future__ import annotations

import csv
import math
import os
import random
import sys
import time
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

# Try to import audio deps
AUDIO_OK = True
try:
    import numpy as np  # type: ignore
    import sounddevice as sd  # type: ignore
except Exception:
    AUDIO_OK = False
    np = None  # type: ignore
    sd = None  # type: ignore


# -----------------------------
# Parameters (edit as you like)
# -----------------------------
@dataclass
class ExperimentParams:
    # Task
    frequency_hz: float = 1000.0          # Tone frequency
    interval_duration_s: float = 0.300    # Duration of each interval
    isi_s: float = 0.250                   # Inter-stimulus interval (gap between intervals)
    ramp_s: float = 0.010                  # On/off cosine ramp for the tone
    sample_rate: int = 44100               # Audio sample rate

    # Staircase (levels in dB relative to full-scale; 0 dBFS = max amplitude 1.0)
    start_level_db: float = -20.0          # Starting signal level (dBFS <= 0)
    min_level_db: float = -60.0            # Lower bound (quieter) to prevent underflow
    max_level_db: float = -3.0             # Upper bound (louder) to prevent clipping

    step_down_db: float = 2.0              # Step size down after 2 correct
    step_up_db: float = 2.0                # Step size up after 1 incorrect
    max_trials: int = 60                   # Safety cap
    max_reversals: int = 12                # Stop after N reversals
    reversals_for_threshold: int = 6       # Use last N reversals to compute threshold

    # 2AFC
    feedback: bool = True                  # Print feedback after each trial
    signal_in_both_intervals: bool = False # If True, add noise ref and vary SNR (not implemented; here False means silence in ref)
    response_keys: Tuple[str, str] = ("1", "2")  # Keys to choose interval 1 or 2

    # Simulated observer (fallback if AUDIO_OK is False or if FORCE_SIMULATION is True)
    FORCE_SIMULATION: bool = False
    sim_threshold_db: float = -30.0        # "True" threshold of the synthetic listener
    sim_slope_beta: float = 1.1            # Steepness of psychometric function (Weibull-like)
    sim_lapse_rate: float = 0.02           # Lapses (upper asymptote < 1.0)


# ---------------------------------
# Utilities: sound generation & I/O
# ---------------------------------
def db_to_amplitude(db: float) -> float:
    """Convert dBFS to linear amplitude (0..1)."""
    return 10 ** (db / 20.0)


def cosine_ramp(signal: "np.ndarray", ramp_samples: int) -> "np.ndarray":
    """Apply a raised-cosine ramp up and down to avoid clicks."""
    if ramp_samples <= 0:
        return signal
    ramp = 0.5 - 0.5 * np.cos(np.linspace(0, math.pi, ramp_samples))
    env = np.ones_like(signal)
    env[:ramp_samples] *= ramp
    env[-ramp_samples:] *= ramp[::-1]
    return signal * env


def make_tone(f_hz: float, dur_s: float, sr: int, amp: float, ramp_s: float) -> "np.ndarray":
    t = np.arange(int(dur_s * sr)) / sr
    wave = np.sin(2 * np.pi * f_hz * t) * amp
    ramp_n = int(ramp_s * sr)
    return cosine_ramp(wave, min(ramp_n, len(wave)//2))


def play_audio(left: "np.ndarray", right: Optional["np.ndarray"] = None, sr: int = 44100):
    """Play mono or stereo buffer (blocks until done)."""
    if right is None:
        buf = left.astype(np.float32)
    else:
        buf = np.column_stack([left, right]).astype(np.float32)
    sd.play(buf, sr, blocking=True)


def prompt_user(prompt: str) -> str:
    """Prompt user and return a single lowercase character (like '1' or '2')."""
    sys.stdout.write(prompt)
    sys.stdout.flush()
    while True:
        ch = sys.stdin.readline().strip().lower()
        if ch:
            return ch


# ---------------------------------
# Staircase logic: 1-up / 2-down
# ---------------------------------
@dataclass
class StaircaseState:
    current_db: float
    trial_index: int = 0
    reversals: int = 0
    last_direction: Optional[int] = None   # +1 up, -1 down, None at start
    reversal_levels: List[float] = field(default_factory=list)
    consecutive_correct: int = 0
    history: List[Tuple[int, int, bool, float]] = field(default_factory=list)  # (trial, signal_interval, correct?, level_db)


class OneUpTwoDown:
    def __init__(self, params: ExperimentParams):
        self.p = params
        clamped = max(min(params.start_level_db, params.max_level_db), params.min_level_db)
        if clamped != params.start_level_db:
            print(f"[Note] start_level_db clamped to {clamped} dB")
        self.state = StaircaseState(current_db=clamped)

    def step(self, correct: bool):
        """
        Update staircase based on correctness.
        - If correct: increase 'consecutive_correct'. When it reaches 2, decrease level (DOWN), reset counter.
        - If incorrect: immediately increase level (UP), reset consecutive_correct.
        """
        s = self.state
        direction = None

        if correct:
            s.consecutive_correct += 1
            if s.consecutive_correct >= 2:
                # DOWN (harder)
                old = s.current_db
                s.current_db = max(s.current_db - self.p.step_down_db, self.p.min_level_db)
                direction = -1
                s.consecutive_correct = 0
        else:
            s.consecutive_correct = 0
            # UP (easier)
            old = s.current_db
            s.current_db = min(s.current_db + self.p.step_up_db, self.p.max_level_db)
            direction = +1

        # reversal check
        if direction is not None and s.last_direction is not None and direction != s.last_direction:
            s.reversals += 1
            s.reversal_levels.append(old)
        if direction is not None:
            s.last_direction = direction

    def done(self) -> bool:
        return (self.state.reversals >= self.p.max_reversals) or (self.state.trial_index >= self.p.max_trials)

    def threshold_estimate(self) -> Optional[float]:
        n = self.p.reversals_for_threshold
        if len(self.state.reversal_levels) >= n:
            return sum(self.state.reversal_levels[-n:]) / n
        return None


# ---------------------------------
# Simulated observer (if no audio)
# ---------------------------------
def simulated_2afc_correct(p: ExperimentParams, level_db: float) -> bool:
    """
    A smooth psychometric function for 2AFC detection.
    Probability correct = gamma + (1 - gamma - lambda) * (1 - exp(-(10^((L - t)/20))^beta))
    For 2AFC, gamma = 0.5.
    """
    gamma = 0.5
    lapse = p.sim_lapse_rate
    # Convert dB to linear relative to threshold
    x = 10 ** ((level_db - p.sim_threshold_db) / 20.0)
    # Weibull-like form
    pc = gamma + (1 - gamma - lapse) * (1 - math.exp(-(x ** p.sim_slope_beta)))
    return random.random() < pc


# ---------------------------------
# Trial runner
# ---------------------------------
def run_trial(params: ExperimentParams, staircase: OneUpTwoDown, csv_writer: csv.writer) -> None:
    s = staircase.state
    s.trial_index += 1

    # Randomize which interval has the signal
    signal_interval = random.choice([1, 2])

    # Prepare audio if possible
    if AUDIO_OK and not params.FORCE_SIMULATION:
        amp = db_to_amplitude(s.current_db)
        tone = make_tone(params.frequency_hz, params.interval_duration_s, params.sample_rate, amp, params.ramp_s)
        silence = np.zeros_like(tone)

        # Interval 1
        if signal_interval == 1:
            buf1 = tone
            buf2 = silence
        else:
            buf1 = silence
            buf2 = tone

        # Play intervals with ISI
        print(f"\nTrial {s.trial_index}: presenting intervals...")
        print("Listen: Interval 1")
        play_audio(buf1, sr=params.sample_rate)
        time.sleep(params.isi_s)
        print("Listen: Interval 2")
        play_audio(buf2, sr=params.sample_rate)

        # Collect response
        resp_prompt = f"Which interval had the tone? Press {params.response_keys[0]} (1st) or {params.response_keys[1]} (2nd): "
        resp_key = prompt_user(resp_prompt)
        if resp_key not in params.response_keys:
            print(f"Invalid key '{resp_key}'. Counting as incorrect.")
            correct = False
        else:
            chosen = 1 if resp_key == params.response_keys[0] else 2
            correct = (chosen == signal_interval)

    else:
        # Simulated observer (no audio or forced)
        correct = simulated_2afc_correct(params, s.current_db)
        print(f"\n[SIM] Trial {s.trial_index}: level {s.current_db:.1f} dBFS -> {'correct' if correct else 'incorrect'} (signal interval={signal_interval})")

    # Feedback & log
    if params.feedback:
        print("✓ Correct!" if correct else "✗ Incorrect.")
    csv_writer.writerow([s.trial_index, signal_interval, int(correct), f"{s.current_db:.3f}"])

    # Update staircase
    staircase.step(correct)

    # Show current status
    thr = staircase.threshold_estimate()
    if thr is not None:
        print(f"Current threshold estimate (mean of last {staircase.p.reversals_for_threshold} reversals): {thr:.2f} dBFS")
    print(f"Next level: {staircase.state.current_db:.2f} dBFS | reversals: {staircase.state.reversals}")


def main():
    print("=== 2AFC (1-up/2-down) Threshold Estimation ===")
    params = ExperimentParams()

    if not AUDIO_OK or params.FORCE_SIMULATION:
        print("[Mode] Running in SIMULATED OBSERVER mode (no audio playback).")
        print("       To run with real audio: install numpy + sounddevice, and set FORCE_SIMULATION=False.")
    else:
        print("[Mode] Real audio playback using numpy + sounddevice.")
        # Probe audio device
        try:
            sd.default.samplerate = params.sample_rate
        except Exception as e:
            print(f"[Warn] Could not set audio sample rate: {e}")

    staircase = OneUpTwoDown(params)

    # Prepare CSV
    outdir = os.path.join(os.getcwd(), "results")
    os.makedirs(outdir, exist_ok=True)
    ts = time.strftime("%Y%m%d-%H%M%S")
    csv_path = os.path.join(outdir, f"2afc_1u2d_{ts}.csv")
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["trial", "signal_interval", "correct(1/0)", "level_dbfs"])

        # Run trials
        while not staircase.done():
            run_trial(params, staircase, writer)

    # Summary
    thr = staircase.threshold_estimate()
    print("\n=== Finished ===")
    print(f"CSV saved to: {csv_path}")
    if thr is None:
        print("Not enough reversals to compute threshold estimate. Consider increasing max_reversals or trials.")
    else:
        print(f"Estimated threshold: {thr:.2f} dBFS (mean of last {staircase.p.reversals_for_threshold} reversals)")

    print("\nTips:")
    print("- Adjust start_level_db so the first few trials are mostly correct (easy).")
    print("- You can change step sizes (step_down_db, step_up_db) for different convergence speed/precision.")
    print("- For real experiments, add practice trials and catch trials, and randomize more parameters if needed.")
    print("- Consider averaging across multiple staircase runs for a robust threshold.")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nExperiment aborted by user.")
